### ISSUE TITLE
Crashes Aida64

### ISSUE THREAD

**Issue by spectra9** [IAmOrion/RSLCD-Viewer#1]
I'm using Aida64 version 6.88.6400 and upon runing RSLCD-Viewer, Aida64 will crash in less than a minute, sometimes immediately. There are no errors, the process just terminated

**Comment by IAmOrion** [comment]
> I'm using Aida64 version 6.88.6400 and upon runing RSLCD-Viewer, Aida64 will crash in less than a minute, sometimes immediately. There are no errors, the process just terminated

Interesting! I've not updated my Aida64 in a while, I will update it during the week and test.  In theory, my app actually doesn't even interact with Aida64 processes at all! 

It's ultimately just a web page viewer, that's it! You can check the source and see for yourself.  This shouldn't have any affect what so ever on Aida64 program.  I would be checking if there's possibly something else affecting it

**Comment by spectra9** [comment]
Yeah, it's pretty weird it just crashes like that with no error

**Comment by IAmOrion** [comment]
> Yeah, it's pretty weird it just crashes like that with no error

Are you 100% certain it's specifically related to my app? like I say, it really doesn't make sense as my app is just a simplified web browser 

Have you tested running AIDA64 on it's own for a prolonged period with RSLCD settings *OFF* without my app running also, have you then tried running AID64 with RSLCD settings ON without my app running for a prolonged period? 
Just to rule out it's not a bug with RSLCD function of AIDA64 that's crashing.

**Comment by spectra9** [comment]
Yes I'm quiet certain. TBH, I'm new to the sensorpanel world since I just bought my 7" LCD a week ago. Since then I've been browsing the aida64 sensorpanel forums, downloading and customizing the sensorpanel files. I've run my PC with sensorpanel active for hours daily now, each day messing around with the sensor items and not once does it crash. 

I came across the remotesensor stuff in the forum and I'm interested to try some animation, which brought me to your app. With the remotesensor active in aida64, without RSLCD-Viewer running, it doesn't crash. If I started RSLCD-Viewer, aida64 will crash shortly after. If I rerun aida64 while RSLCD-Viewer is still running, same thing happen, it will crash shortly after. If I point the url to something else other than 127.0.0.1 and rerun aida64, then it doesn't crash. 

However I have found something interesting. Just for kicks, I try putting http://127.0.0.1:80 in my Opera browser and aida64 does NOT crash. BUT, when I begin to refresh the page rapidly, it sometimes crash. Also one time when I try to refresh the browser while aida64 is still showing the progress "Detecting Sensor Information" it will crash, this time with error message, EAccessViolation. I'm beginning to think this is a bug in aida64 itself, maybe it has something to do with the way it handle frequent request or something

**Comment by spectra9** [comment]
The issue in this [thread](https://forums.aida64.com/topic/11188-启动-remotesensor-lcd-功能错误/) seems to be similar to what I'm experiencing. Alas there's no solution posted yet <sigh>

**Comment by spectra9** [comment]
I've reverted back to Aida64 6.70.6000 and it no longer crashes either with browser or your app. Definitely an issue on Finalwire's end

**Comment by IAmOrion** [comment]
> I've reverted back to Aida64 6.70.6000 and it no longer crashes either with browser or your app. Definitely an issue on Finalwire's end

ahhh interesting!! Sad that isn't yet fixed (having looked over that thread) but happy that it's not MY app causing the issue! ha.  Thank you for the updates and info

**Comment by spectra9** [comment]
> 
> ahhh interesting!! Sad that isn't yet fixed (having looked over that thread) but happy that it's not MY app causing the issue! ha. Thank you for the updates and info

No prob, part of the tinkering process :-D. Final update, trying the latest beta now. Well, for simple panel with only the time, date and cpu clock sensors, it "seems" fine. I then tried with the sonic one, and it crash consistently within 10 minutes lol. Hopefully they figure out soon what's wrong, would really love to try some of the animated ones
