### ISSUE TITLE
There is a problem during compilation

### ISSUE THREAD

**Issue by osmancitci** [IAmOrion/RSLCD-Viewer#2]
Compilation started...
1>------ Compilation started: Project: AIDA64SensorPanelBrowser_v2, Configuration: Debug Any CPU ------
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3493,5): warning MSB3327: The code signing certificate was not found in the current user's Windows certificate store. To fix this, either disable code signing for ClickOnce deployment or install the certificate into the certificate store.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3493,5): error MSB3323: The code signing certificate for ClickOnce deployment was not found in the certificate store.
========== Compilation: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Compilation started at 22:44 and took 00.207 seconds ==========

**Comment by IAmOrion** [comment]
This is a problem with your setup, not my code.
Try to disable the code signing as it suggests
